# Generated by Django 6.0.5 on 2026-06-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_remove_employee_details_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='salary_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
